#!/bin/bash

set -e

function build {
    cd puzzles/
    cargo build
    cd -
}

function run {
    build
    cd puzzles/
    RUST_BACKTRACE=full ./target/debug/puzzles
    cd -
}

#
# List available tasks
#
function help {
    echo "$0 <task> <args>"
    echo "Tasks:"
    compgen -A function | cat -n
}

TIMEFORMAT="Task completed in %3lR"
time "${@:-help}"